### ISSUE TITLE
Update CRS

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/spData#41]
https://github.com/r-spatial/sf/issues/1319#event-3191940552

**Comment by Nowosad** [comment]
@rsbivand I have replaced old crs attributes with the new ones for the `sf` objects in this package (e.g., `st_crs(nz) = st_crs(nz)`). Should I do something similar to the `sp` objects? How?

**Comment by rsbivand** [comment]
If you could point me to an **sp** object, I can try it out. I `data/`, I can mostly only see `data.frame` objects, and some very old debris. In `inst/shapes`, the `"CRS"` will get created on reading - if GDAL >=3 and PROJ >= 6, (and **rgdal** >= 1.5), the WKT2 string will be generated automatically.

**Comment by Nowosad** [comment]
**sp** objects (I was able to find):

- `state.vbm`
- `house`
- `elect80`
- `SplashDams`

**Comment by rsbivand** [comment]
```
library(spData)
data(house)
slot(house, "proj4string")
comment(slot(house, "proj4string"))
nc <- sp::CRS(slot(slot(house, "proj4string"), "projargs"))
slot(house, "proj4string") <- nc
slot(house, "proj4string")
cat(comment(slot(house, "proj4string")), "\n")
```
Briefly, if you trust the outcomes:

```
slot(house, "proj4string") <- sp::CRS(slot(slot(house, "proj4string"), "projargs"))
```
is a one-liner. This is importing the legacy Proj string and exporting to Proj (losing an implied `+datum=`) and WKT2 (going into the CRS comment).

Pre-PROJ 6/GDAL 3 will not see or use the comment.

**Comment by Nowosad** [comment]
Thanks @rsbivand. I checked the data and it should be fine after updating the `"proj4string"` slot.

PR: https://github.com/Nowosad/spData/pull/42 - should we merge it now or after **rgdal** >= 1.5 is on CRAN?

**Comment by rsbivand** [comment]
Maybe run `CMD check` in four contexts, A[1:2]:  **sf**, **sp** and **rgdal** from CRAN (1: PROJ < 6, GDAL < 3; 2: PROJ >= 6, GDAL >= 3), and B[1:2] **sf** and **sp** from CRAN with **rgdal** from R-forge. I think that if **spData** passes win-builder (A1), and either of [AB]2, you can even submit  **spData** to CRAN as far as **sp** objects are concerned, because the use of `comment()` goes under the S4 radar. Then when I get to submitting **rgdal**, I would not expect to see any pushback from **spData** - seeing increases in NOTE/WARNING/ERROR in CRAN's revdep checks.

**Comment by Nowosad** [comment]
Thanks @rsbivand. I have done all four `CMD check`s - they went fine. I plan to update the package on CRAN tomorrow.

**Comment by Nowosad** [comment]
On CRAN now - https://cran.r-project.org/web/packages/spData/index.html.
